### ISSUE TITLE
User is displayed with two horizontal scroll bar on list grid

### ISSUE THREAD

**Issue by kamalsingh** [blackbaud/skyux-list-builder#113]
Expected behavior: User should display consistent scroll bar 

Actual behavior: Initially showing one (bottom) scroll bar but when we increase column width it shows both the horizontal scroll bar (bottom and top).

Steps to reproduce: 1. Open a grid with columns width more than parent's width.
2. By default on grid tile it is showing bottom horizontal scroll bar. 
3. Increase the width of any column, now it shows both the horizontal scroll bar. 
4. Decrease the width of column to as per earlier but it still shows both the horizontal scroll bar. 

Ideally either it shows both the horizontal scroll bar on initial page load or after reducing column width it should show one horizontal scroll bar i.e. initial behavior (by default showing only bottom horizontal scroll bar on grid load). 
Is there any way to show only one (bottom) horizontal scroll bar when column width exceeds?

Severity: low

Impact: low

[AB#1585833](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1585833)

**Comment by Blackbaud-SteveBrush** [comment]
Due to the priority of this issue, we're recommending consumers use [data entry grid](https://developer.blackbaud.com/skyux/components/data-entry-grid) instead.
