### ISSUE TITLE
Investigate multiple calls to getData()

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-list-builder#12]
Nautilus has reported that their list-view-grid makes multiple calls to their API, causing a lot of unnecessary request units to go through Azure DB.

Our initial research on this topic showed that this mostly happens on initial load of the grid, although we should check to see what happens when the list state changes via filtering, searching, etc...

Is this a bug? Can we do something to mitigate?

**Comment by Blackbaud-AlexKingman** [comment]
From Spencer Murphy (nautilus - permissions UI)

Did some digging and here's what I'm seeing:
Initial Load: 2
Search: 1
Sort: 1
Filter: 1
Add/Remove Columns: 2
Move Columns: 2
On the initial load, Trevor you were correct. The first request has the old filters/search/sort options and the second one has new updated values

**Comment by Blackbaud-TrevorBurch** [comment]
In `skyux-grids@3.1.3` and `skyux-list-builder-view-grids@3.0.2`
