### ISSUE TITLE
List filters does not emit appliedFiltersChange for custom views

### ISSUE THREAD

**Issue by Blackbaud-VanesaiXiong** [blackbaud/skyux-list-builder#121]
### Expected behavior
The `appliedFiltersChange` event should fire on filter change, when using a custom view.

### Actual behavior
The `appliedFiltersChange` event is not firing for custom views.

#### Setup
1. Create a `sky-list`
2. Bind `appliedFiltersChange` to a method
2. Add a `sky-list-toolbar' section to the list
3. Add a `sky-list-filter-button` section to the toolbar
4. Bind `filterButtonClick` to something that will apply a filter to the list
5. Add a `sky-list-filter-summary' section to the toolbar
6. Add a custom view to the list (instead of `sky-list-view-checklist`, or `sky-list-view-grid`)

#### Steps
1. Go to the list
2. Apply a filter
2.1. expected: `appliedFiltersChange` fires and invokes the method bound in Setup Step 2
2.2 actual: nothing fires and the method is not invoked
3. Dismiss the filter
3.1. expected: `appliedFiltersChange` fires and invokes the method bound in Setup Step 2
3.2 actual: nothing fires and the method is not invoked

see [StachBlitz example](https://stackblitz.com/edit/angular-m6t8pw?file=src%2Fapp%2Flist-filters-demo.component.html)

### Severity
Low

### Impact
Low

### Notes
- only affects custom views
- there is [a workaround](https://blackbaud.visualstudio.com/Products/_git/skyux-spa-volunteers/pullrequest/143460?_a=files)
- link to [slack discussion](https://blackbaud.slack.com/archives/C3TQ4C0KG/p1607382242232700)

[AB#1646134](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1646134)

**Comment by Blackbaud-AlexKingman** [comment]
Hi @Blackbaud-VanesaiXiong, thanks for submitting. Slack is down at the moment, so I'm not sure if you discussed this... but I did take a look at your stackblitz and noticed something - The custom view needs to be an actual component that `extends` the `ListViewComponent` for the list builder to register it as a list view. Once you do that, the filters should start to work normally as expected. Would you mind giving that a try and letting me know if that solves your issue?

**Comment by Blackbaud-VanesaiXiong** [comment]
@Blackbaud-AlexKingman I've updated the [stackblitz example](https://stackblitz.com/edit/angular-m6t8pw?file=src%2Fapp%2Flist-filters-demo.component.html) to implement a custom `ListViewComponent`, but the issue still persists. Please take a look and make sure it was done correctly.

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-VanesaiXiong You'll need to add a `forwardRef` provider to your component, like so...
```
providers: [
    {
        provide: ListViewComponent, useExisting: forwardRef(() => CustomViewComponent)
    }
  ]
```

Does that work?

**Comment by Blackbaud-VanesaiXiong** [comment]
@Blackbaud-AlexKingman Yep. That works. Thanks for the help!
