### ISSUE TITLE
List filter summary shows default value when multiple filters are active

### ISSUE THREAD

**Issue by Blackbaud-VanesaiXiong** [blackbaud/skyux-list-builder#122]
### Expected behavior
The default value for a filter should not show in the summary, when multiple filters are applied.

### Actual behavior
The default value shows in the summary, if multiple filters are applied and at least one is not the default.

### Steps to reproduce
1. Apply at least one default filter and one non-default filter

see [StackBlitz example](https://blackbaud.slack.com/archives/C3TQ4C0KG/p1608075109307100?thread_ts=1608075080.306800&cid=C3TQ4C0KG)

### Severity
Low

### Impact
Low

### Notes
- You can workaround, by omitting the default filter(s) before applying - provided those defaults do not filter out anything
- link to [slack thread](https://blackbaud.slack.com/archives/C3TQ4C0KG/p1608075080306800)

[AB#1652444](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1652444)

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.0.3`
