### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError for list filters

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-list-builder#125]
**From Tom Ramsey:**

I tried updating https://dev.azure.com/blackbaud/Products/_git/skyux-spa-entitlements-prod-support/pullrequest/145867?_a=files with the fix for popovers, but it appears to break backwards compatibility (breaking both the tiles when you serve the branch locally, and the tests which we have for our tiles).  I believe the problem is this change: https://github.com/blackbaud/skyux-list-builder/commit/22f7701b112d51dc9f7daed22fd39837a85cc0c7

The error is:

```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngForOf: [object Object]'. Current value: 'ngForOf: '
```

Specifically, changing the filter array in that way causes the `ngFor` in https://github.com/blackbaud/skyux-list-builder/blob/master/src/app/public/modules/list-filters/list-filter-summary.component.html to recalculate unexpectedly, breaking the digest cycle.

**StackBlitz:** https://stackblitz.com/edit/angular-m6t8pw-bdzgkm?file=src%2Fapp%2Flist-filters-demo.component.html

[AB#1664102](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1664102)

**Comment by Blackbaud-KrisMahon** [comment]
We have also hit this same issue in `skyux-spa-event-mgmt`, but it appears to work fine in `skyux-spa-participant`.  Both SPAs use the filter summary component, so I'm not sure what's different at this time.
