### ISSUE TITLE
Skyux-data-manager-column_chooser - User is displayed with unselected column headers when 'Show only selected items' filter applied 

### ISSUE THREAD

**Issue by kamalsingh** [blackbaud/skyux-list-builder#133]
### Expected behavior: 
Only selected column should be visible when 'Show only selected items' filter applied.

### Actual behavior:
User is displayed with unselected column headers

### Steps to reproduce:
1. Navigate to https://developer.blackbaud.com/skyux-data-manager/docs/data-manager?docs-active-tab=development (skyux data manager for reference code).
2. Select a few list items 
3. Click on 'Show only selected items' filter
4. Unselect few items or click on clear-all and observe the behavior
It is showing unselected items as well in the list even we have checked 'Show only selected items' filter check box.

### Severity: 
Low

### Impact:
Low

Please find the attached file for UI reference. 
![transaction history filter](https://user-images.githubusercontent.com/5894278/132340207-4691dfc2-20cc-4717-98ec-655414019d71.JPG)
![Column chooser filter](https://user-images.githubusercontent.com/5894278/132340211-f6976ac3-1d86-49de-a4a4-c88b34313ba4.JPG)

**Comment by Blackbaud-SteveBrush** [comment]
This has been addressed.
