### ISSUE TITLE
refreshDisplayedItems causes a ExpressionChangedAfterItHasBeenCheckedError when last item on page is deleted

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-list-builder#19]
### Expected behavior
`refreshDisplayedItems()` should be able to handle pagination properly when the last item is removed from a page. It should automatically navigate the user back to the previous page.

### Actual behavior
If you delete the last row of a grid, it throws an `ExpressionChangedAfterItHasBeenCheckedError`.

### Steps to reproduce
https://stackblitz.com/edit/skyux-list-edge-case

**Comment by Blackbaud-TrevorBurch** [comment]
In `list-builder-view-grids` `3.0.1`
