### ISSUE TITLE
Port > list-builder repeater view

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux-list-builder#20]

**Comment by Blackbaud-ToddRoberts** [comment]
design doc https://blackbaudinc.box.com/s/1ko585y2qe19xrnsbrf8d46wxn02sbti

**Comment by Blackbaud-SteveBrush** [comment]
Closing; repeaters will work out-of-the-box with Data Manager.
See: https://github.com/blackbaud/skyux-lists/issues/108
