### ISSUE TITLE
Port > list-builder card view

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux-list-builder#21]

**Comment by Blackbaud-ToddRoberts** [comment]
https://blackbaudinc.box.com/s/epdv09sreq0vpr9t5fz88lyu6zog4f22

**Comment by Blackbaud-SteveBrush** [comment]
Closing; cards will work out-of-the-box with Data Manager. 
See: https://github.com/blackbaud/skyux-lists/issues/108
