### ISSUE TITLE
Unable to dynamically show or hide sky-list-toolbar-item

### ISSUE THREAD

**Issue by blackbaud-elizabethsmith** [blackbaud/skyux-list-builder#23]
### Expected behavior

When using `*ngIf="foo"` to toggle the presence of a `sky-list-toolbar-item`, the component should respect the changed value of `foo`.   This is how the non-list `sky-toolbar-item` also behaves.

### Actual behavior

It appears the initial value of `foo` is all that is respected. 

### Steps to reproduce

In `my-component.ts`, we have:

```
public foo: boolean = false;
....
public ngOnInit(): void {
  this.myService.getFooValue().subscribe(result => {
    this.foo = result;
    this.changeDetector.markForCheck();
  }
}
```

In `my-component.html`, we have:
```
<sky-list [dataProvider]="listDataProvider" [appliedFilters]="listFilters" (appliedFiltersChange)="handleFiltersChanged($event)" #myList>
  <sky-list-toolbar>
    <sky-list-toolbar-item *ngIf="foo">
      <ng-template>
            <button class="sky-btn sky-btn-primary" (click)="showSomething()">
              <span>My button</span>
            </button>
          </ng-template>
    </sky-list-toolbar-item>
  </sky-list-toolbar>
</sky-list>
```

If `foo` comes back true, the toolbar item is not displayed.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.4`
