### ISSUE TITLE
Dragging columns on mobile does not work well when list extends past the viewport

### ISSUE THREAD

**Issue by blackbaud-GavinNicol** [blackbaud/skyux-list-builder#29]
### Expected behavior

On mobile, dragging column headers on a list should change the order of the columns.

### Actual behavior

When dragging on mobile, if the list extends past the viewport then dragging column headers also causes the list to move which results in the column header never changing positions

### Steps to reproduce

1. Create a list with multiple columns that extends past the mobile view port.
2. On mobile, touch and hold the column header and drag to a new position
3. Notice the list moves with the column

### Impact

Users on mobile are not able to re-order columns on large lists

**Comment by Blackbaud-TrevorBurch** [comment]
In `skyux/grids` `3.2.1`
