### ISSUE TITLE
multiselect action bar not fully supported  when using dataprovider for skylist

### ISSUE THREAD

**Issue by LaymanHacks** [blackbaud/skyux-list-builder#44]
### Expected behavior
`Only show selected items` should hide/show selected items in the list when multiselect is enabled.

### Actual behavior
`Only show selected items` works correctly when using data property but when using a custom data provider fails to hide/show selected items in the list when multiselect is enabled.

### Steps to reproduce
Add a sky list with a custom data provider and set the enableMultiselect="true" on a child sky-list-view-grid. With a few of the items selected check the `Only show selected items` option on the action bar and the list of items will not change.

**Comment by Blackbaud-AlexKingman** [comment]
Discussed with @LaymanHacks  --> When using the `dataProvider`, the consumer is responsible for handling all filters. While unclear, the "show only selected" checkbox is actually a filter. We're going to close this issue for the time being, but we all agree there is a need to clarify this in the docs, and provide a demo to show how to do it. You can follow that progress here: blackbaud/skyux2-docs#466
