### ISSUE TITLE
appliedFiltersChange event does not fire every time when using inline remove

### ISSUE THREAD

**Issue by blackbaud-GavinNicol** [blackbaud/skyux-list-builder#49]
### Expected behavior

When removing an applied filter via the inline `x`, the `appliedFiltersChange` event should be fire.

### Actual behavior

The `appliedFiltersChange` seems to only be fired on every other removal starting with the 2nd. For example. If 4 filters are applied and I remove one via the inline `x` then the event is not fired. If I remove a 2nd then the event is fired. If I remove a 3rd, the event is not fired.

### Steps to reproduce

1. Create a sky list and pass in a method for the appliedFiltersChange event
2. Add some filters to the list
3. Remove filters via the inline delete

![image](https://user-images.githubusercontent.com/17765781/59212810-5be09e00-8b81-11e9-9484-8348a0569d60.png)

4. Notice the appliedFiltersChange is not fired for every removal.

**Comment by blackbaud-brandonhare** [comment]
This affects modal filters as well. I just encountered this.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.5.1`
