### ISSUE TITLE
Multi-select toolbar on sky-list-view-checklist looks bad on mobile

### ISSUE THREAD

**Issue by Blackbaud-BenRice** [blackbaud/skyux-list-builder#96]
### Expected behavior
The built-in multi-select toolbar that is shown with a multi-select sky-list-view-checklist should render in way that is clean and does not take up 1/4 of the screen.  Hiding that toolbar or collapsing it might be a potential improvement for the mobile experience.

### Actual behavior
The spacing around the 'select all' and 'clear all' seems excessive. The 'only show selected' checkbox also seems a little off.

![multiselectfilter png](https://user-images.githubusercontent.com/13256225/86254465-d365de80-bb83-11ea-837c-bec048c3f310.jpg)

### Steps to reproduce
View the demo for the list view checklist on your phone.  

### Severity
Low

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-ToddRoberts Any thoughts?

**Comment by Blackbaud-ToddRoberts** [comment]
I could see updating the layout to something like this:

![image](https://user-images.githubusercontent.com/13765813/86261548-b2ee5200-bb8c-11ea-8c17-4f42e567c65e.png)

We can't really shrink the whitespace due to click target size requirements.

**Comment by Blackbaud-BenRice** [comment]
I think that's a big improvement. Should we consider degrading functionality in mobile view?  Do any of those options go away to give more real estate for the list of values?
